# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevelDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1024, unique=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('created', models.DateTimeField(blank=True, default=None, null=True)),
                ('changed', models.DateTimeField(blank=True, default=None, null=True)),
                ('registar', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('source', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('raw', models.TextField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='engine.TopLevelDomain')),
            ],
        ),
        migrations.CreateModel(
            name='WhoisServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, default=None, max_length=1024, unique=True)),
                ('source', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('queryFormat', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('availablePattern', models.CharField(blank=True, default=None, max_length=1024, null=True)),
                ('errorPattern', models.CharField(blank=True, default=None, max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='topleveldomain',
            name='whois',
            field=models.ManyToManyField(blank=True, default=None, related_name='tld', to='engine.WhoisServer'),
        ),
    ]
