# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('registered', models.DateTimeField(blank=True, default=None, null=True)),
                ('expired', models.DateTimeField(blank=True, default=None, null=True)),
                ('whois', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='engine.WhoisServer')),
            ],
        ),
    ]
