# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisServiceResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('raw', models.TextField()),
                ('parsed', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='engine.Domain')),
                ('whois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='engine.WhoisServer')),
            ],
        ),
    ]
